server:
  port: 8082
#  ssl:
                      #    key-store: .keystore
                      #    key-store-password: 123456
                      #    key-store-type: JKS
                      #    key-alias: tomcat
spring:
  thymeleaf:
    cache: false
    mode: HTML5